version: 2.1
jobs:
  build_docker:
    machine: true

    steps:
      - checkout
      - run: docker build -t petersonryan/website:$CIRCLE_SHA1 .
      - run: docker login -u petersonryan -p $DOCKERHUB_ACCESS_KEY
      - run: docker push petersonryan/website:$CIRCLE_SHA1

workflows:
  buildDocker:
    jobs:
      - build_docker
