version: 2.1
jobs:
  build_docker:
    machine: true

    steps:
      - checkout
      - run: docker build -t personal/website:$CIRCLE_SHA1 .

workflows:
  buildDocker:
    jobs:
      - build_docker
