version: 2.1
jobs:
  build_docker:
    machine: true

    working_directory: ~/tmp

    steps:
      - run: cd ~/tmp
      - run: docker build -t personal/website:$CIRCLE_SHA1 .

workflows:
  buildDocker:
    jobs:
      - build_docker
