version: 2.1
jobs:
  build_docker:
    machine: true

    steps:
      - checkout
      - run: docker build -t petersonryan/website:$CIRCLE_SHA1 .
      - run: docker login -u petersonryan -p $DOCKERHUB_ACCESS_KEY
      - run: docker push petersonryan/website:$CIRCLE_SHA1

  deploy:
    machine: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "19:fe:86:96:75:ee:57:43:a5:b1:cf:a6:f4:e4:46:f1"
            
      - run: ssh-keyscan petersonryan.com
      - run: ssh deploy@petersonryan.com "sh /home/deploy/scripts/website.sh $CIRCLE_SHA1"

workflows:
  buildDocker:
    jobs:
      - build_docker
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master
