version: 2.1
jobs:
  build_docker:
    machine: true

    steps:
      - checkout
      - run: docker build -t petersonryan/website:$CIRCLE_SHA1 .
      - run: docker login -u petersonryan -p $DOCKERHUB_ACCESS_KEY
      - run: docker push petersonryan/website:$CIRCLE_SHA1

  deploy:
    machine: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "2a:19:7a:b4:84:85:92:13:f6:f3:9e:e2:be:bf:2a:99"
            
      - run: ssh-keyscan petersonryan.com
      - run: ssh deploy@petersonryan.com "sh /home/deploy/scripts/website.sh $CIRCLE_SHA1"

workflows:
  buildDocker:
    jobs:
      - build_docker
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master
